### ISSUE TITLE
A /public/m3-db.gz adatbazis nem frissul

### ISSUE THREAD

**Issue by seci** [a-sync/m3-keresheto-archivum#3]
Az éles oldalról elérhető naponta frissülő adatbázis export a [/public/m3-db.gz](https://m3.devs.space/public/m3-db.gz) útvonalon.

Sajnos ugy tunik, hogy utiljara 2022-11-04-en frissult, azota nem.

Koszi a hibaelharitast!

**Comment by a-sync** [comment]
szia,
a teljes export (/backup) csak hetente frissül!

most ráfrissítettem manuálisan, amúgy holnap frissült volna :)

**Comment by seci** [comment]
OK, koszi, csak a multkori name-server hiba miatt gondoltam, hogy leallt, merthogy "naponta frissülő adatbázis export" nem frissult naponta :)

**Comment by a-sync** [comment]
ha megnézed a readme-t a csv export a napi: /public/m3-db.csv.gz

a biztonsági mentés az meg heti. (kb 1 éve fogta magát és elkúródott az adatbázisban az összes ékezet és mivel nem másnapra lett észrevéve nem maradt visszaállítható mentés...ezért lett inkább heti)
